---
title: "Graphics for Communication"
session: "04"
subtitle: "R Markdown for Medicine"
author: Alison Hill
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "assets/css/my-theme.css", "assets/css/my-fonts.css"]
    seal: false 
    lib_dir: libs
    nature:
      highlightStyle: tomorrow-night-eighties
      highlightLanguage: ["r", "yaml", "markdown"]
      slideNumberFormat: "" 
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "https://platform.twitter.com/widgets.js"
    includes:
      in_header: assets/header.html  
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r packages, include=FALSE}
library(countdown)
```


class: title-slide, center, middle

<span class="fa-stack fa-4x">
  <i class="fa fa-circle fa-stack-2x" style="color: #ffffffcc;"></i>
  <strong class="fa-stack-1x" style="color:#3b4245;">`r rmarkdown::metadata$session`</strong>
</span> 

# `r rmarkdown::metadata$title`

## `r rmarkdown::metadata$subtitle`

### `r rmarkdown::metadata$author` &#183; RStudio

#### [rmd4medicine.netlify.com/](https://rmd4medicine.netlify.com/)


<!-- this ends up being the title slide since seal = FALSE-->

---
layout: true

<div class="my-footer"><span>rstudio.cloud/link</span></div>

<!-- this adds the link footer to all slides, depends on my-footer class in css-->


---
class: middle, center, inverse

<span class="fa-stack fa-4x">
  <i class="fa fa-circle fa-stack-2x" style="color: #ffffffcc;"></i>
  <strong class="fas fa-gifts" style="color:#E7553C;"></strong>
</span> 


# Time to wrap-up!



