# (PART) Data + Workflows {-}

# Introduction {-}

Check out a new Rmd file here.

This will sort of be where we hopefully get into a bit of a groove

# Projects and files

What goes where

# Importing data

Options like excel, googlesheets

# Using data

primarily `here` package stuff with file paths

# Dealing with other people's data 

janitor::clean_names() is a life-saver

# R Markdown collections

At some point, after using R Markdown for awhile, you may find yourself experiencing growing pains working with single R Markdown documents. If you do a lot of data wrangling and EDA, you'll find your R Markdown documents can become quite long, making it hard to find what you need when you need it. That is when you know it is time to evolve! 

A few ways to evolve your R Markdown ways: 

1. Start making good use of .R scripts and "outsource" those using `source(wrangle.R)`. 

1. Start using R Markdown child documents.

1. *Recommended*: start building an R Markdown collection per project. This is what we'll demo now. We think this is the most flexible workflow that allows your research project to grow and change along with your ideas and needs.

`bookdown::word_document2`

# Uplevel {#up-flow}

## GitHub {#git-flow}

## Collaborating

+ https://noamross.github.io/redoc/
+ https://github.com/ekothe/rmdrive

## Datapasta

Sharing data

## Reprex

Getting help
